### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by fmchowdhury** [epfl-dlab/GenIE#1]
May I ask what is the license of GenIE codes and also data?

**Comment by martinj96** [comment]
Sure! GenIE is licensed under the terms of the MIT License – I just added the information to the repository. Regarding the data, it has been adapted from prior work. So while the additions fall under the MIT licence, the original data might not, so please verify that your application complies with the other licences. You can find the respective references in the paper.

Hope this helps!
