### ISSUE TITLE
I could not find .utils.py or folder

### ISSUE THREAD

**Issue by 924ahn** [epfl-dlab/GenIE#10]
Hi, I'm trying to use your code.
To exercise with your demo code, there's a code "from .utils import label_smoothed_nll_loss".
But I could not find that .utils.
Where can I find it?
Thank you for read my issue.

**Comment by martinj96** [comment]
Hi,

[Here](https://github.com/epfl-dlab/GenIE/blob/c53d52f598c2940e00f753c97b3baf4ba144fc03/genie/models/utils.py#L6) it is!

Cheers,
Martin
