### ISSUE TITLE
Unable to reproduce GenIE/notebooks/Demo.ipynb output

### ISSUE THREAD

**Issue by AndreiCComan** [epfl-dlab/GenIE#2]
Hello, thank you for your valuable work. I found it very interesting!

I have tried to run the `GenIE/notebooks/Demo.ipynb` notebook and I found some mismatches with the provided outputs. I was wondering if you have any idea of why this is happening.

---

For instance, under the **Unconstrained Generation** subsection, I get the following output:

`[[{'text': ' <sub> KSAZ <rel> headquarters location <obj> Phoenix, Arizona <et>', 'log_prob': -0.1369926631450653}, {'text': ' <sub> KSAZ-TV <rel> headquarters location <obj> Phoenix, Arizona <et>', 'log_prob': -0.200978085398674}]]`

while the expected one is:

`[[{'text': ' <sub> KTRK, Carson <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.19589225947856903},
  {'text': ' <sub> KTRK, Carson <rel> located in the administrative territorial entity <obj> Arizona <et> <sub> KSAZ <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.2037668377161026}]]`

---

Same behaviour under the **Constrained Generation** subsection. For instance, the **Small Schema Constrainted Generation** output is:

`[[{'text': ' <sub> Arizona <rel> capital <obj> Phoenix, Arizona <et>',
   'log_prob': -0.21632088720798492},
  {'text': ' <sub> Phoenix, Arizona <rel> capital of <obj> Arizona <et> <sub> Arizona <rel> capital <obj> Phoenix, Arizona <et>',
   'log_prob': -0.3067542612552643}]]`

while the expected one is:

`[[{'text': ' <sub> Fox Broadcasting Company <rel> located in the administrative territorial entity <obj> Arizona <et> <sub> Phoenix, Arizona <rel> capital of <obj> Arizona <et> <sub> Arizona <rel> capital <obj> Phoenix, Arizona <et>',
   'log_prob': -0.43319371342658997},
  {'text': ' <sub> Fox Broadcasting Company <rel> headquarters location <obj> Arizona <et> <sub> Phoenix, Arizona <rel> capital of <obj> Arizona <et> <sub> Arizona <rel> capital <obj> Phoenix, Arizona <et>',
   'log_prob': -0.4518451988697052}]]` 

---

Similarly, the output under the **Large Schema Constrainted Generation** is:

`[[{'text': ' <sub> KSAZ <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.1369926631450653},
  {'text': ' <sub> KSAZ-TV <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.200978085398674}]]`

while the expected one is:

`[[{'text': ' <sub> KTRK <rel> headquarters location <obj> Phoenix, Arizona <et> <sub> KSAZ-TV <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.22215303778648376},
  {'text': ' <sub> KTRK <rel> headquarters location <obj> Phoenix, Arizona <et>',
   'log_prob': -0.22950957715511322}]]`

---

**PS**: I also had to downgrade `torchmetrics` to `0.6.0` as the default `conda` installation through the provided `bash.sh` script threw the following `ImportError`:

> ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

**Comment by martinj96** [comment]
Hey Andrei, 

Thanks for providing me with the details!

In my environment, I can successfully reproduce the outputs. It seems to me that this discrepancy comes from the sampling paired with some differences in the library versions – the model's outputs are qualitatively similar. Thanks for reporting the necessity for downgrading `torchmetrics`. I would bet that our torch versions also differ, so I updated the `pip_requirements.txt`. Please check if you get the same outputs in an environment with the updated requirements.

While trying to fix the problem, I noticed that the model is actually not in eval mode when sampling from it outside of the test loop, so I fixed that as well and updated the demo accordingly. This makes me even more convinced of the above hypothesis.

Sorry for coming back to you a bit late, and feel free to reopen the issue if you encounter any problems. 

Cheers,
Martin
