### ISSUE TITLE
Is it possible to adapt genie to DBpedia?

### ISSUE THREAD

**Issue by Fcabla** [epfl-dlab/GenIE#3]
Hi, I am working on a tool to translate text to RDF format under the DBpedia ontology. I think your tool is great and I would like to use it in my project, but I have seen that you use the wikidata ontology. 

Do you think it is possible to use another ontology? what would be needed? 
I believe that DBpedia Spotlight does something similar to what GENRE does

Thanks in advance

**Comment by martinj96** [comment]
Hey Fernando, 

Sorry for the late reply, I missed this issue.

I don't know all the details of how DBpedia is structured, but you could potentially:
1) Try to match GenIE's output to DBpedia (for this, you would need a mapping between Wikidata entities and relations and their DBpedia counterparts). This case does not require re-training the model.
2) Get training data that corresponds to DBpedia (DBpediaTriplets-to-Text) and retrain the model.

Let me know if you have any other questions!

Cheers,
Martin
