### ISSUE TITLE
how was `martinjosifoski/genie-rw` tokenizer obtained?

### ISSUE THREAD

**Issue by chenxwh** [epfl-dlab/GenIE#4]
Hi @martinj96,

I have a question regarding the random initialisation (which is the default right?) It is not clear to me [here](https://github.com/epfl-dlab/GenIE/blob/master/genie/models/genie_base_pl.py#L77) how  
```python
tokenizer = transformers.BartTokenizer.from_pretrained("martinjosifoski/genie-rw")
```
is trained/obtained beforehand?

Thank you!

**Comment by martinj96** [comment]
Hi Chenxi,

Yes, the randomly initialized model used the default random initialization from HF. 

Similarly, the GenIE tokenizer corresponds to the default [BartTokenizer](https://huggingface.co/docs/transformers/model_doc/bart#transformers.BartTokenizer) available on HF -- the tokenizer in `martinjosifoski/genie-rw` is meant to serve as a snapshot of the exact version that was used for GenIE (and is a copy of the default BART tokenizer).

Let me know if you have any other questions! 

Martin
