### ISSUE TITLE
`protobuf` package version mismatch

### ISSUE THREAD

**Issue by Saibo-creator** [epfl-dlab/GenIE#7]
## Error Message

```terminal
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

The package version of `protobuf` installed by default is `4.22.0`  in my case, a fix is to downgrade the package into 3.20.x. 
We could also consider specifying the version in the `requirements.txt`

## Reproduction
- Running `setup.py` 
- Start the `Demo.ipynb` notebook
- Run the block 

```python
"""Load the Model"""
from genie.models import GeniePL

ckpt_name = "genie_r.ckpt"
path_to_checkpoint = os.path.join(DATA_DIR, 'models', ckpt_name)
model = GeniePL.load_from_checkpoint(checkpoint_path=path_to_checkpoint)
```

## Fix
Explicitly set `protobuf` package version in the `requirements.txt`: `protobuf==3.20`

There may have better ways to fix the error.

**Comment by martinj96** [comment]
Thanks for the fix, Saibo!
