### ISSUE TITLE
Broken link for custom prefix tree construction

### ISSUE THREAD

**Issue by sMamooler** [epfl-dlab/GenIE#9]
Hello,

The link to the custom prefix tree construction cell seems to be broken in these two cells in `demo.ipynb`:
`To construct a prefix trie for your custom set of strings see this section.`
and 
`The last two examples illustrate how the generation for any of the GenIE models can be constrained with an arbitrary prefix tries. See how you can construct your custom prefix trie`

**Comment by martinj96** [comment]
Hi @sMamooler,

Indeed, thanks for letting me know -- I just updated it! Although I presume you figured it out, I'd like to note that the link was only for convenience and was trying to point to a section lower in the notebook. 

Finally, if you intend to use our code/models in a project, checking out [this](https://github.com/epfl-dlab/SynthIE) repository might be useful for you -- it implements everything from this repository and adds some more (additional models, more flexible decoding, etc.).

Cheers,
Martin

**Comment by sMamooler** [comment]
Thanks for the reply @martinj96!
SynthIE can be very useful for our project!
